# Generated by Django 4.0.5 on 2022-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de Usuario')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo de Usuario')),
                ('Suscrito', models.BooleanField(default=False, verbose_name='suscripcion de Usuario')),
                ('fechaSuscrito', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha Suscrito de Usuario')),
                ('Admin', models.BooleanField(default=False, verbose_name='Isadmin de Usuario')),
            ],
        ),
    ]
